# Use this file to create the conda environment:
# conda env create -f requirements.yaml

name: piperfim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.4
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=7.0.3
  - ipywidgets=8.1.1
  - widgetsnbextension=4.0.9
  - jupyter_server=2.7.3
  - nbconvert=7.8.0
  - nbformat=5.9.2
  - matplotlib-inline=0.1.6
  - rdkit=2023.03.2
  - flask=3.0.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - psutil
  - plotly
  - tqdm
  - pip
  - pip:
      - venn
      - geoparse
      - biopython